@startuml コンピューターが扱うデータ
actor computer
boundary 2進数
control 10進数
entity Foo4
database Foo5
collections Foo6
computer -> 2進数 : 1 and 0
computer -> 10進数 : 重み
computer -> Foo4 : To entity
computer -> Foo5 : To database
computer -> Foo6 : To collections
@enduml
